[BaseOperationCost]
    StorePerByte = 10
    DataCopyPerByte = 10
    CompilePerByte = 10
    PersitPerByte = 10
    ReleasePerByte = 10
    AoTPreparePerByte = 10

[BaseOpsAPICost]
    GetSCAddress       = 10
    GetOwnerAddress    = 10
    IsSmartContract    = 10
    GetShardOfAddress  = 10
    GetExternalBalance = 10
    GetBlockHash = 10
    GetOriginalTxHash = 10
    GetPrevTxHash = 10
    GetCurrentTxHash = 10
    TransferValue = 10
    GetArgument = 10
    GetFunction = 10
    GetNumArguments = 10
    StorageStore = 10
    StorageLoad = 10
    GetCaller = 10
    GetCallValue = 10
    Log = 10
    Finish = 10
    SignalError = 10
    GetBlockTimeStamp = 10
    GetGasLeft = 10
    Int64GetArgument = 10
    Int64StorageStore = 10
    Int64StorageLoad = 10
    Int64Finish = 10
    GetStateRootHash = 10
    GetBlockNonce = 10
    GetBlockEpoch = 10
    GetBlockRound = 10
    GetBlockRandomSeed = 10
    ExecuteOnSameContext = 10
    ExecuteOnDestContext = 10
    DelegateExecution = 10
    ExecuteReadOnly = 10
    AsyncCallStep = 10
    AsyncCallbackGasLock = 10
    CreateAsyncCall = 10
    SetAsyncCallback = 10
    SetAsyncGroupCallback = 10
    SetAsyncContextCallback = 10
    GetCallbackClosure = 10
    CreateContract = 10
    GetReturnData = 10
    GetNumReturnData = 10
    GetReturnDataSize = 10
    CleanReturnData = 10
    DeleteFromReturnData = 10
    GetCodeMetadata = 10
    GetCodeHash = 10
    IsBuiltinFunction = 10
    IsReservedFunctionName = 10
    GetRoundTime = 10
    EpochStartBlockTimeStamp = 10
    EpochStartBlockNonce = 10
    EpochStartBlockRound = 10

[EthAPICost]
    UseGas = 10
    GetAddress = 10
    GetExternalBalance = 10
    GetBlockHash = 10
    Call = 10
    CallDataCopy = 10
    GetCallDataSize = 10
    CallCode = 10
    CallDelegate = 10
    CallStatic = 10
    StorageStore = 10
    StorageLoad = 10
    GetCaller = 10
    GetCallValue = 10
    CodeCopy = 10
    GetCodeSize = 10
    GetBlockCoinbase = 10
    Create = 10
    GetBlockDifficulty = 10
    ExternalCodeCopy = 10
    GetExternalCodeSize = 10
    GetGasLeft = 10
    GetBlockGasLimit = 10
    GetTxGasPrice = 10
    Log = 10
    GetBlockNumber = 10
    GetTxOrigin = 10
    Finish = 10
    Revert = 10
    GetReturnDataSize = 10
    ReturnDataCopy = 10
    SelfDestruct = 10
    GetBlockTimeStamp = 10

    [BigIntAPICost]
    BigIntNew = 10
    BigIntUnsignedByteLength = 10
    BigIntSignedByteLength = 10
    BigIntGetUnsignedBytes = 10
    BigIntGetSignedBytes = 10
    BigIntSetUnsignedBytes = 10
    BigIntSetSignedBytes = 10
    BigIntIsInt64 = 10
    BigIntGetInt64 = 10
    BigIntSetInt64 = 10
    BigIntAdd = 10
    BigIntSub = 10
    BigIntMul = 10
    BigIntSqrt = 10
    BigIntPow = 10
    BigIntLog = 10
    BigIntTDiv = 10
    BigIntTMod = 10
    BigIntEDiv = 10
    BigIntEMod = 10
    BigIntAbs = 10
    BigIntNeg = 10
    BigIntSign = 10
    BigIntCmp = 10
    BigIntNot = 10
    BigIntAnd = 10
    BigIntOr = 10
    BigIntXor = 10
    BigIntShr = 10
    BigIntShl = 10
    BigIntFinishUnsigned = 10
    BigIntFinishSigned = 10
    BigIntStorageLoadUnsigned = 10
    BigIntStorageStoreUnsigned = 10
    BigIntGetUnsignedArgument = 10
    BigIntGetSignedArgument = 10
    BigIntGetCallValue = 10
    BigIntGetExternalBalance = 10
    CopyPerByteForTooBig = 10

    [BigFloatAPICost]
    BigFloatNewFromParts = 10
    BigFloatAdd = 10
    BigFloatSub = 10
    BigFloatMul = 10
    BigFloatDiv = 10
    BigFloatTruncate = 10
    BigFloatNeg = 10
    BigFloatClone = 10
    BigFloatCmp = 10
    BigFloatAbs = 10
    BigFloatSqrt = 10
    BigFloatPow = 10
    BigFloatPowPerIteration = 10
    BigFloatFloor = 10
    BigFloatCeil = 10
    BigFloatIsInt = 10
    BigFloatSetBigInt = 10
    BigFloatSetInt64 = 10
    BigFloatGetConst = 10

[CryptoAPICost]
    SHA256 = 10
    Keccak256 = 10
    EllipticCurveNew = 10
    AddECC = 10
    DoubleECC = 10
    IsOnCurveECC = 10
    ScalarMultECC = 10
    MarshalECC = 10
    MarshalCompressedECC = 10
    UnmarshalECC = 10
    UnmarshalCompressedECC = 10
    GenerateKeyECC = 10
    EncodeDERSig = 10

[ManagedBufferAPICost]
    MBufferNew = 10
    MBufferNewFromBytes = 10
    MBufferGetLength = 10
    MBufferGetBytes = 10
    MBufferGetByteSlice = 10
    MBufferCopyByteSlice = 10
    MBufferSetBytes = 10
    MBufferAppend = 10
    MBufferAppendBytes = 10
    MBufferToBigIntUnsigned = 10
    MBufferToBigIntSigned = 10
    MBufferFromBigIntUnsigned = 10
    MBufferFromBigIntSigned = 10
    MBufferToSmallIntUnsigned = 10
    MBufferToSmallIntSigned = 10
    MBufferFromSmallIntUnsigned = 10
    MBufferFromSmallIntSigned = 10
    MBufferToBigFloat = 10
    MBufferFromBigFloat = 10
    MBufferStorageStore = 10
    MBufferStorageLoad = 10
    MBufferGetArgument = 10
    MBufferFinish = 10
    MBufferSetRandom = 10

[ManagedMapAPICost]
    ManagedMapNew      = 10
    ManagedMapPut      = 10
    ManagedMapGet      = 10
    ManagedMapRemove   = 10
    ManagedMapContains = 10

[WASMOpcodeCost]
    AtomicFence = 1
    AtomicNotify = 1
    Block = 1
    Br = 1
    BrIf = 1
    BrTable = 1
    Call = 1
    CallIndirect = 1
    Catch = 1
    CatchAll = 1
    DataDrop = 1
    Delegate = 1
    Drop = 1
    ElemDrop = 1
    Else = 1
    End = 1
    F32Abs = 1
    F32Add = 1
    F32Ceil = 1
    F32Const = 1
    F32ConvertI32S = 1
    F32ConvertI32U = 1
    F32ConvertI64S = 1
    F32ConvertI64U = 1
    F32Copysign = 1
    F32DemoteF64 = 1
    F32Div = 1
    F32Eq = 1
    F32Floor = 1
    F32Ge = 1
    F32Gt = 1
    F32Le = 1
    F32Load = 1
    F32Lt = 1
    F32Max = 1
    F32Min = 1
    F32Mul = 1
    F32Ne = 1
    F32Nearest = 1
    F32Neg = 1
    F32ReinterpretI32 = 1
    F32Sqrt = 1
    F32Store = 1
    F32Sub = 1
    F32Trunc = 1
    F32x4Abs = 1
    F32x4Add = 1
    F32x4Ceil = 1
    F32x4ConvertI32x4S = 1
    F32x4ConvertI32x4U = 1
    F32x4DemoteF64x2Zero = 1
    F32x4Div = 1
    F32x4Eq = 1
    F32x4ExtractLane = 1
    F32x4Floor = 1
    F32x4Ge = 1
    F32x4Gt = 1
    F32x4Le = 1
    F32x4Lt = 1
    F32x4Max = 1
    F32x4Min = 1
    F32x4Mul = 1
    F32x4Ne = 1
    F32x4Nearest = 1
    F32x4Neg = 1
    F32x4PMax = 1
    F32x4PMin = 1
    F32x4ReplaceLane = 1
    F32x4Splat = 1
    F32x4Sqrt = 1
    F32x4Sub = 1
    F32x4Trunc = 1
    F64Abs = 1
    F64Add = 1
    F64Ceil = 1
    F64Const = 1
    F64ConvertI32S = 1
    F64ConvertI32U = 1
    F64ConvertI64S = 1
    F64ConvertI64U = 1
    F64Copysign = 1
    F64Div = 1
    F64Eq = 1
    F64Floor = 1
    F64Ge = 1
    F64Gt = 1
    F64Le = 1
    F64Load = 1
    F64Lt = 1
    F64Max = 1
    F64Min = 1
    F64Mul = 1
    F64Ne = 1
    F64Nearest = 1
    F64Neg = 1
    F64PromoteF32 = 1
    F64ReinterpretI64 = 1
    F64Sqrt = 1
    F64Store = 1
    F64Sub = 1
    F64Trunc = 1
    F64x2Abs = 1
    F64x2Add = 1
    F64x2Ceil = 1
    F64x2ConvertI64x2S = 1
    F64x2ConvertI64x2U = 1
    F64x2ConvertLowI32x4S = 1
    F64x2ConvertLowI32x4U = 1
    F64x2Div = 1
    F64x2Eq = 1
    F64x2ExtractLane = 1
    F64x2Floor = 1
    F64x2Ge = 1
    F64x2Gt = 1
    F64x2Le = 1
    F64x2Lt = 1
    F64x2Max = 1
    F64x2Min = 1
    F64x2Mul = 1
    F64x2Ne = 1
    F64x2Nearest = 1
    F64x2Neg = 1
    F64x2PMax = 1
    F64x2PMin = 1
    F64x2PromoteLowF32x4 = 1
    F64x2ReplaceLane = 1
    F64x2Splat = 1
    F64x2Sqrt = 1
    F64x2Sub = 1
    F64x2Trunc = 1
    GlobalGet = 1
    GlobalSet = 1
    I16x8Abs = 1
    I16x8Add = 1
    I16x8AddSatS = 1
    I16x8AddSatU = 1
    I16x8AddSaturateS = 1
    I16x8AddSaturateU = 1
    I16x8AllTrue = 1
    I16x8AnyTrue = 1
    I16x8Bitmask = 1
    I16x8Eq = 1
    I16x8ExtAddPairwiseI8x16S = 1
    I16x8ExtAddPairwiseI8x16U = 1
    I16x8ExtMulHighI8x16S = 1
    I16x8ExtMulHighI8x16U = 1
    I16x8ExtMulLowI8x16S = 1
    I16x8ExtMulLowI8x16U = 1
    I16x8ExtendHighI8x16S = 1
    I16x8ExtendHighI8x16U = 1
    I16x8ExtendLowI8x16S = 1
    I16x8ExtendLowI8x16U = 1
    I16x8ExtractLaneS = 1
    I16x8ExtractLaneU = 1
    I16x8GeS = 1
    I16x8GeU = 1
    I16x8GtS = 1
    I16x8GtU = 1
    I16x8LeS = 1
    I16x8LeU = 1
    I16x8Load8x8S = 1
    I16x8Load8x8U = 1
    I16x8LtS = 1
    I16x8LtU = 1
    I16x8MaxS = 1
    I16x8MaxU = 1
    I16x8MinS = 1
    I16x8MinU = 1
    I16x8Mul = 1
    I16x8NarrowI32x4S = 1
    I16x8NarrowI32x4U = 1
    I16x8Ne = 1
    I16x8Neg = 1
    I16x8Q15MulrSatS = 1
    I16x8ReplaceLane = 1
    I16x8RoundingAverageU = 1
    I16x8Shl = 1
    I16x8ShrS = 1
    I16x8ShrU = 1
    I16x8Splat = 1
    I16x8Sub = 1
    I16x8SubSatS = 1
    I16x8SubSatU = 1
    I16x8SubSaturateS = 1
    I16x8SubSaturateU = 1
    I16x8WidenHighI8x16S = 1
    I16x8WidenHighI8x16U = 1
    I16x8WidenLowI8x16S = 1
    I16x8WidenLowI8x16U = 1
    I32Add = 1
    I32And = 1
    I32AtomicLoad = 1
    I32AtomicLoad16U = 1
    I32AtomicLoad8U = 1
    I32AtomicRmw16AddU = 1
    I32AtomicRmw16AndU = 1
    I32AtomicRmw16CmpxchgU = 1
    I32AtomicRmw16OrU = 1
    I32AtomicRmw16SubU = 1
    I32AtomicRmw16XchgU = 1
    I32AtomicRmw16XorU = 1
    I32AtomicRmw8AddU = 1
    I32AtomicRmw8AndU = 1
    I32AtomicRmw8CmpxchgU = 1
    I32AtomicRmw8OrU = 1
    I32AtomicRmw8SubU = 1
    I32AtomicRmw8XchgU = 1
    I32AtomicRmw8XorU = 1
    I32AtomicRmwAdd = 1
    I32AtomicRmwAnd = 1
    I32AtomicRmwCmpxchg = 1
    I32AtomicRmwOr = 1
    I32AtomicRmwSub = 1
    I32AtomicRmwXchg = 1
    I32AtomicRmwXor = 1
    I32AtomicStore = 1
    I32AtomicStore16 = 1
    I32AtomicStore8 = 1
    I32AtomicWait = 1
    I32Clz = 1
    I32Const = 1
    I32Ctz = 1
    I32DivS = 1
    I32DivU = 1
    I32Eq = 1
    I32Eqz = 1
    I32Extend16S = 1
    I32Extend8S = 1
    I32GeS = 1
    I32GeU = 1
    I32GtS = 1
    I32GtU = 1
    I32LeS = 1
    I32LeU = 1
    I32Load = 1
    I32Load16S = 1
    I32Load16U = 1
    I32Load8S = 1
    I32Load8U = 1
    I32LtS = 1
    I32LtU = 1
    I32Mul = 1
    I32Ne = 1
    I32Or = 1
    I32Popcnt = 1
    I32ReinterpretF32 = 1
    I32RemS = 1
    I32RemU = 1
    I32Rotl = 1
    I32Rotr = 1
    I32Shl = 1
    I32ShrS = 1
    I32ShrU = 1
    I32Store = 1
    I32Store16 = 1
    I32Store8 = 1
    I32Sub = 1
    I32TruncF32S = 1
    I32TruncF32U = 1
    I32TruncF64S = 1
    I32TruncF64U = 1
    I32TruncSatF32S = 1
    I32TruncSatF32U = 1
    I32TruncSatF64S = 1
    I32TruncSatF64U = 1
    I32WrapI64 = 1
    I32Xor = 1
    I32x4Abs = 1
    I32x4Add = 1
    I32x4AllTrue = 1
    I32x4AnyTrue = 1
    I32x4Bitmask = 1
    I32x4DotI16x8S = 1
    I32x4Eq = 1
    I32x4ExtAddPairwiseI16x8S = 1
    I32x4ExtAddPairwiseI16x8U = 1
    I32x4ExtMulHighI16x8S = 1
    I32x4ExtMulHighI16x8U = 1
    I32x4ExtMulLowI16x8S = 1
    I32x4ExtMulLowI16x8U = 1
    I32x4ExtendHighI16x8S = 1
    I32x4ExtendHighI16x8U = 1
    I32x4ExtendLowI16x8S = 1
    I32x4ExtendLowI16x8U = 1
    I32x4ExtractLane = 1
    I32x4GeS = 1
    I32x4GeU = 1
    I32x4GtS = 1
    I32x4GtU = 1
    I32x4LeS = 1
    I32x4LeU = 1
    I32x4Load16x4S = 1
    I32x4Load16x4U = 1
    I32x4LtS = 1
    I32x4LtU = 1
    I32x4MaxS = 1
    I32x4MaxU = 1
    I32x4MinS = 1
    I32x4MinU = 1
    I32x4Mul = 1
    I32x4Ne = 1
    I32x4Neg = 1
    I32x4ReplaceLane = 1
    I32x4Shl = 1
    I32x4ShrS = 1
    I32x4ShrU = 1
    I32x4Splat = 1
    I32x4Sub = 1
    I32x4TruncSatF32x4S = 1
    I32x4TruncSatF32x4U = 1
    I32x4TruncSatF64x2SZero = 1
    I32x4TruncSatF64x2UZero = 1
    I32x4WidenHighI16x8S = 1
    I32x4WidenHighI16x8U = 1
    I32x4WidenLowI16x8S = 1
    I32x4WidenLowI16x8U = 1
    I64Add = 1
    I64And = 1
    I64AtomicLoad = 1
    I64AtomicLoad16U = 1
    I64AtomicLoad32U = 1
    I64AtomicLoad8U = 1
    I64AtomicRmw16AddU = 1
    I64AtomicRmw16AndU = 1
    I64AtomicRmw16CmpxchgU = 1
    I64AtomicRmw16OrU = 1
    I64AtomicRmw16SubU = 1
    I64AtomicRmw16XchgU = 1
    I64AtomicRmw16XorU = 1
    I64AtomicRmw32AddU = 1
    I64AtomicRmw32AndU = 1
    I64AtomicRmw32CmpxchgU = 1
    I64AtomicRmw32OrU = 1
    I64AtomicRmw32SubU = 1
    I64AtomicRmw32XchgU = 1
    I64AtomicRmw32XorU = 1
    I64AtomicRmw8AddU = 1
    I64AtomicRmw8AndU = 1
    I64AtomicRmw8CmpxchgU = 1
    I64AtomicRmw8OrU = 1
    I64AtomicRmw8SubU = 1
    I64AtomicRmw8XchgU = 1
    I64AtomicRmw8XorU = 1
    I64AtomicRmwAdd = 1
    I64AtomicRmwAnd = 1
    I64AtomicRmwCmpxchg = 1
    I64AtomicRmwOr = 1
    I64AtomicRmwSub = 1
    I64AtomicRmwXchg = 1
    I64AtomicRmwXor = 1
    I64AtomicStore = 1
    I64AtomicStore16 = 1
    I64AtomicStore32 = 1
    I64AtomicStore8 = 1
    I64AtomicWait = 1
    I64Clz = 1
    I64Const = 1
    I64Ctz = 1
    I64DivS = 1
    I64DivU = 1
    I64Eq = 1
    I64Eqz = 1
    I64Extend16S = 1
    I64Extend32S = 1
    I64Extend8S = 1
    I64ExtendI32S = 1
    I64ExtendI32U = 1
    I64GeS = 1
    I64GeU = 1
    I64GtS = 1
    I64GtU = 1
    I64LeS = 1
    I64LeU = 1
    I64Load = 1
    I64Load16S = 1
    I64Load16U = 1
    I64Load32S = 1
    I64Load32U = 1
    I64Load8S = 1
    I64Load8U = 1
    I64LtS = 1
    I64LtU = 1
    I64Mul = 1
    I64Ne = 1
    I64Or = 1
    I64Popcnt = 1
    I64ReinterpretF64 = 1
    I64RemS = 1
    I64RemU = 1
    I64Rotl = 1
    I64Rotr = 1
    I64Shl = 1
    I64ShrS = 1
    I64ShrU = 1
    I64Store = 1
    I64Store16 = 1
    I64Store32 = 1
    I64Store8 = 1
    I64Sub = 1
    I64TruncF32S = 1
    I64TruncF32U = 1
    I64TruncF64S = 1
    I64TruncF64U = 1
    I64TruncSatF32S = 1
    I64TruncSatF32U = 1
    I64TruncSatF64S = 1
    I64TruncSatF64U = 1
    I64Xor = 1
    I64x2Abs = 1
    I64x2Add = 1
    I64x2AllTrue = 1
    I64x2AnyTrue = 1
    I64x2Bitmask = 1
    I64x2Eq = 1
    I64x2ExtMulHighI32x4S = 1
    I64x2ExtMulHighI32x4U = 1
    I64x2ExtMulLowI32x4S = 1
    I64x2ExtMulLowI32x4U = 1
    I64x2ExtendHighI32x4S = 1
    I64x2ExtendHighI32x4U = 1
    I64x2ExtendLowI32x4S = 1
    I64x2ExtendLowI32x4U = 1
    I64x2ExtractLane = 1
    I64x2GeS = 1
    I64x2GtS = 1
    I64x2LeS = 1
    I64x2Load32x2S = 1
    I64x2Load32x2U = 1
    I64x2LtS = 1
    I64x2Mul = 1
    I64x2Ne = 1
    I64x2Neg = 1
    I64x2ReplaceLane = 1
    I64x2Shl = 1
    I64x2ShrS = 1
    I64x2ShrU = 1
    I64x2Splat = 1
    I64x2Sub = 1
    I64x2TruncSatF64x2S = 1
    I64x2TruncSatF64x2U = 1
    I8x16Abs = 1
    I8x16Add = 1
    I8x16AddSatS = 1
    I8x16AddSatU = 1
    I8x16AddSaturateS = 1
    I8x16AddSaturateU = 1
    I8x16AllTrue = 1
    I8x16AnyTrue = 1
    I8x16Bitmask = 1
    I8x16Eq = 1
    I8x16ExtractLaneS = 1
    I8x16ExtractLaneU = 1
    I8x16GeS = 1
    I8x16GeU = 1
    I8x16GtS = 1
    I8x16GtU = 1
    I8x16LeS = 1
    I8x16LeU = 1
    I8x16LtS = 1
    I8x16LtU = 1
    I8x16MaxS = 1
    I8x16MaxU = 1
    I8x16MinS = 1
    I8x16MinU = 1
    I8x16Mul = 1
    I8x16NarrowI16x8S = 1
    I8x16NarrowI16x8U = 1
    I8x16Ne = 1
    I8x16Neg = 1
    I8x16Popcnt = 1
    I8x16ReplaceLane = 1
    I8x16RoundingAverageU = 1
    I8x16Shl = 1
    I8x16ShrS = 1
    I8x16ShrU = 1
    I8x16Shuffle = 1
    I8x16Splat = 1
    I8x16Sub = 1
    I8x16SubSatS = 1
    I8x16SubSatU = 1
    I8x16SubSaturateS = 1
    I8x16SubSaturateU = 1
    I8x16Swizzle = 1
    If = 1
    LocalGet = 1
    LocalSet = 1
    LocalTee = 1
    LocalAllocate = 1
    LocalsUnmetered = 1
    Loop = 1
    MaxMemoryGrow = 1
    MaxMemoryGrowDelta = 1
    MemoryAtomicNotify = 1
    MemoryAtomicWait32 = 1
    MemoryAtomicWait64 = 1
    MemoryCopy = 1
    MemoryFill = 1
    MemoryGrow = 1
    MemoryInit = 1
    MemorySize = 1
    Nop = 1
    RefFunc = 1
    RefIsNull = 1
    RefNull = 1
    Rethrow = 1
    Return = 1
    ReturnCall = 1
    ReturnCallIndirect = 1
    Select = 1
    TableCopy = 1
    TableFill = 1
    TableGet = 1
    TableGrow = 1
    TableInit = 1
    TableSet = 1
    TableSize = 1
    Throw = 1
    Try = 1
    TypedSelect = 1
    Unreachable = 1
    Unwind = 1
    V128And = 1
    V128AndNot = 1
    V128AnyTrue = 1
    V128Bitselect = 1
    V128Const = 1
    V128Load = 1
    V128Load16Lane = 1
    V128Load16Splat = 1
    V128Load16x4S = 1
    V128Load16x4U = 1
    V128Load32Lane = 1
    V128Load32Splat = 1
    V128Load32Zero = 1
    V128Load32x2S = 1
    V128Load32x2U = 1
    V128Load64Lane = 1
    V128Load64Splat = 1
    V128Load64Zero = 1
    V128Load8Lane = 1
    V128Load8Splat = 1
    V128Load8x8S = 1
    V128Load8x8U = 1
    V128Not = 1
    V128Or = 1
    V128Store = 1
    V128Store16Lane = 1
    V128Store32Lane = 1
    V128Store64Lane = 1
    V128Store8Lane = 1
    V128Xor = 1
    V16x8LoadSplat = 1
    V32x4LoadSplat = 1
    V64x2LoadSplat = 1
    V8x16LoadSplat = 1
    V8x16Shuffle = 1
    V8x16Swizzle = 1
